### ISSUE TITLE
Convert WCL files to LAS

### ISSUE THREAD

**Issue by slbin** [alt-lu/pywellcad#135]
Dear expert,

Our purpose is to convert WCL files to LAS automatically without manual intervention. 
When I use borehole.file_export() to export as LAS file, it seems that I have to click a button since the UI below will pop up when I run the code.

![image](https://github.com/alt-lu/pywellcad/assets/24591040/deb8189c-9a03-4baa-82b0-2995295da80e)

Is there any better way to do this?

**Comment by m-schubert** [comment]
Hi @slbin, we'd prefer to keep the GitHub issues section focused on `pywellcad` development rather than technical support. If you'd like technical support, please feel free to contact our support team at support@alt.lu, or post on StackOverflow. It's also worthwhile having a good read through the documentation - your question is answered in the [documentation for `Borehole.file_export()`](https://pywellcad.readthedocs.io/en/v0.1.0/borehole.html#wellcad.com.Borehole.file_export)

**Comment by slbin** [comment]
> Hi @slbin, we'd prefer to keep the GitHub issues section focused on `pywellcad` development rather than technical support. If you'd like technical support, please feel free to contact our support team at [support@alt.lu](mailto:support@alt.lu), or post on StackOverflow. It's also worthwhile having a good read through the documentation - your question is answered in the [documentation for `Borehole.file_export()`](https://pywellcad.readthedocs.io/en/v0.1.0/borehole.html#wellcad.com.Borehole.file_export)


Hi Matthew. I was being stupid. Well noted and thanks a lot.
